services:
  - docker

language: python
python:
  - "3.8"
before_install:
  - sudo apt-get update
  - sudo apt-get install libhunspell-dev
install:
  - pip install pipenv
  - pipenv install
  - pip install pytest nose coveralls
script:
  - docker build -t tts-service . -f docker/dockerfile
  - nosetests --with-coverage
after_success:
  coveralls
